version: '3'

services:
  backend:
    container_name: "django4"
    build:
      context: ./backend/docker
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
    command: sh -c "cd /app && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ../mysql_data:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: django_db
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: passwd

  frontend:
    container_name: "node21"
    build: ./frontend/app
    volumes:
      - ./frontend/app:/usr/src/app
    command: sh -c "cd /usr/src/app && npm start"
    ports:
      - 3000:3000
