# Generated by Django 4.2 on 2024-01-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productinfo_productpilgrimage_delete_testdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpilgrimage',
            old_name='name',
            new_name='location',
        ),
    ]
