# Generated by Django 4.2 on 2024-01-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_name_productpilgrimage_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpilgrimage',
            old_name='x_position',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='productpilgrimage',
            old_name='y_position',
            new_name='longitude',
        ),
    ]
