# Generated by Django 4.2 on 2024-02-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_x_position_productpilgrimage_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpilgrimage',
            name='gone',
            field=models.BooleanField(default=False),
        ),
    ]
